// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/calionauta/cali-go-stack/features/todo"

// Layout wraps the todo app in a full HTML document with:
//   - DaisyUI + TailwindCSS classes (assumes the CDN/embedded CSS is loaded
//     by the consuming page)
//   - Datastar JS loaded from the embedded copy under /static/datastar.js
//   - #toast-container for stacked toasts (bottom-right, column-reverse)
//   - <style> block for the toast animations + progress bar
//
// Pages call Layout(title, signals) and embed their content as children.
func Layout(title string, signals todo.Signals) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" data-theme=\"light\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `features/todo/components/layout.templ`, Line: 19, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/daisyui@5.6.13/dist/full.min.css\"><script src=\"https://cdn.tailwindcss.com\"></script><script type=\"module\" src=\"/static/datastar.js\"></script><style>\n\t\t\t\t/* Stacking container: fixed bottom-right, toasts stack upward. */\n\t\t\t\t#toast-container {\n\t\t\t\t\tz-index: 100;\n\t\t\t\t\tposition: fixed;\n\t\t\t\t\tright: 1rem;\n\t\t\t\t\tbottom: 1rem;\n\t\t\t\t\tdisplay: flex;\n\t\t\t\t\tflex-direction: column-reverse;\n\t\t\t\t\tgap: 0.5rem;\n\t\t\t\t\tmax-width: 24rem;\n\t\t\t\t}\n\n\t\t\t\t/* Toast entrance: hidden + scaled-down, then the .open class\n\t\t\t\t   transitions it in. Driven by data-class on the toast root. */\n\t\t\t\t.toast-msg {\n\t\t\t\t\topacity: 0;\n\t\t\t\t\ttransform: scale(0.9) translateY(50px);\n\t\t\t\t\ttransition: transform 0.5s, opacity 0.5s;\n\t\t\t\t}\n\t\t\t\t.toast-msg.open {\n\t\t\t\t\ttransform: scale(1) translateY(0);\n\t\t\t\t\topacity: 1;\n\t\t\t\t}\n\n\t\t\t\t/* Progress bar: shrinks from 100% to 0% over the toast lifetime.\n\t\t\t\t   Matches the toast-remove delay (3s for success/info, 8s for\n\t\t\t\t   error) — the CSS animation here fires immediately on mount\n\t\t\t\t   because the bar is rendered together with the toast root. */\n\t\t\t\t.toast-timer-bar {\n\t\t\t\t\theight: 3px;\n\t\t\t\t\tborder-radius: 999px;\n\t\t\t\t\tbackground: oklch(0.872 0.01 258.338 / 0.3);\n\t\t\t\t\tanimation: toast-shrink 3s linear forwards;\n\t\t\t\t}\n\t\t\t\t.toast-msg:has(.alert-error) .toast-timer-bar {\n\t\t\t\t\tanimation-duration: 8s;\n\t\t\t\t}\n\t\t\t\t@keyframes toast-shrink {\n\t\t\t\t\tfrom { width: 100%; }\n\t\t\t\t\tto { width: 0%; }\n\t\t\t\t}\n\t\t\t</style></head><body class=\"bg-base-200 min-h-screen\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = TodoList(signals).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div id=\"toast-container\"></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
