// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// RealtimeStream opens the persistent Server-Sent Events stream that keeps
// every connected browser in sync. It is rendered ONCE, from Layout, so the
// realtime wiring lives in exactly one place and cannot drift per-page.
//
// WHY THE HIDDEN-BUTTON + SCRIPT PATTERN (not data-on:load):
// Datastar v1 does not fire data-on:load / data-on:init on <div> or <body>,
// so a card using `data-on:load={ "@get('/api/todos/stream')" }` silently
// never opened the stream — broadcasts were registered on the server but no
// browser ever received them, and the connected-clients count stayed wrong.
// The fix is a hidden button whose data-on:click is a real @get (Datastar
// keeps that open as a persistent SSE), clicked by this script once Datastar
// signals readiness. Centralising it here means a single regression test can
// assert the opener + script are present on every page.
//
// streamURL is the SSE endpoint to open (e.g. "/api/todos/stream"). Other
// features pass their own endpoint; the mechanism is identical.
func RealtimeStream(streamURL string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button id=\"sse-opener\" class=\"hidden\" data-on:click=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue("@get('" + streamURL + "')")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `features/todo/components/realtime.templ`, Line: 23, Col: 45}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" aria-hidden=\"true\"></button><script type=\"module\">\n\t\t// Open the realtime SSE stream once Datastar has initialised.\n\t\t// Datastar v1 does not fire data-on:load/init on <div>/<body>, so we\n\t\t// click the hidden #sse-opener button (whose data-on:click is a real\n\t\t// @get that Datastar keeps open as a persistent SSE). Datastar\n\t\t// dispatches the \"datastar-ready\" event when it has processed the\n\t\t// DOM; we click on that, with a timeout fallback in case the event\n\t\t// already fired before this listener attached.\n\t\t(function () {\n\t\t\tfunction openSSE() {\n\t\t\t\tvar b = document.getElementById('sse-opener');\n\t\t\t\tif (b && !b.dataset.opened) { b.dataset.opened = '1'; b.click(); }\n\t\t\t}\n\t\t\tdocument.addEventListener('datastar-ready', openSSE);\n\t\t\t// Fallback if datastar-ready already fired.\n\t\t\tsetTimeout(openSSE, 300);\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
