package db

import (
	"log/slog"

	"github.com/pocketbase/pocketbase"
	"github.com/pocketbase/pocketbase/core"
)

// SeedDefaults creates default collections and data on first run.
//
// Collections are NOT auto-created by PocketBase on first access — that comment
// was a lie. Each collection must be explicitly registered here so a fresh
// `make dev` clone can create todos out of the box without hitting the admin
// UI first.
func SeedDefaults(app *pocketbase.PocketBase) error {
	app.OnServe().BindFunc(func(se *core.ServeEvent) error {
		if err := ensureTodosCollection(se.App); err != nil {
			slog.Error("seed: ensureTodosCollection failed", "error", err)
		}
		return se.Next()
	})
	return nil
}

// ensureTodosCollection creates the "todos" collection if it doesn't exist.
// Uses the default PocketBase schema: text title, bool completed, two date
// fields for created/updated. The id field is auto-added by PocketBase
// (15 chars, pattern ^[a-z0-9]+$, autogenerated).
func ensureTodosCollection(app core.App) error {
	if _, err := app.FindCollectionByNameOrId("todos"); err == nil {
		return nil // already exists
	}

	col := core.NewBaseCollection("todos")
	col.Fields.Add(
		&core.TextField{Name: "title", Required: true},
		&core.BoolField{Name: "completed"},
		&core.DateField{Name: "created"},
		&core.DateField{Name: "updated"},
	)
	if err := app.Save(col); err != nil {
		return err
	}
	slog.Info("seed: created todos collection")
	return nil
}
